apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp-deploy
  labels:
    app: myapp-deploy
    tier: front-end
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
